FROM node:16
WORKDIR /code
RUN npm config set registry https://registry.npmmirror.com \
&& npm config set disturl https://npmmirror.com/dist --location=global \
&& npm i --location=global pnpm \
&& pnpm install \
&& pnpm build